/** Logos estáticos CoinGecko (CDN público) por id ou símbolo — suplementa Trust/1inch. */

export const COINGECKO_LOGO_BY_ID: Record<string, string> = {
  bitcoin: 'https://assets.coingecko.com/coins/images/1/small/bitcoin.png',
  ethereum: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
  cardano: 'https://assets.coingecko.com/coins/images/975/small/cardano.png',
  solana: 'https://assets.coingecko.com/coins/images/4128/small/solana.png',
  sui: 'https://assets.coingecko.com/coins/images/26375/small/sui_asset.jpeg',
  aptos: 'https://assets.coingecko.com/coins/images/26455/small/aptos_round.png',
  cosmos: 'https://assets.coingecko.com/coins/images/1481/small/cosmos_hub.png',
  osmosis: 'https://assets.coingecko.com/coins/images/16724/small/osmosis.jpeg',
  'the-open-network': 'https://assets.coingecko.com/coins/images/17980/small/ton_symbol.png',
  ton: 'https://assets.coingecko.com/coins/images/17980/small/ton_symbol.png',
  stellar: 'https://assets.coingecko.com/coins/images/100/small/Stellar_symbol_black_square.png',
  ripple: 'https://assets.coingecko.com/coins/images/44/small/xrp-symbol-white-128.png',
  dogecoin: 'https://assets.coingecko.com/coins/images/5/small/dogecoin.png',
  litecoin: 'https://assets.coingecko.com/coins/images/2/small/litecoin.png',
  polkadot: 'https://assets.coingecko.com/coins/images/12171/small/polkadot.png',
  chainlink: 'https://assets.coingecko.com/coins/images/877/small/chainlink-new-logo.png',
  avalanche: 'https://assets.coingecko.com/coins/images/12559/small/Avalanche_Circle_RedWhite_Trans.png',
  polygon: 'https://assets.coingecko.com/coins/images/4713/small/matic-token-icon.png',
  matic: 'https://assets.coingecko.com/coins/images/4713/small/matic-token-icon.png',
  optimism: 'https://assets.coingecko.com/coins/images/25244/small/Optimism.png',
  arbitrum: 'https://assets.coingecko.com/coins/images/16547/small/arb.jpg',
  base: 'https://assets.coingecko.com/coins/images/31065/small/base.png',
  near: 'https://assets.coingecko.com/coins/images/10365/small/near.jpg',
  tron: 'https://assets.coingecko.com/coins/images/1094/small/tron-logo.png',
  monad: 'https://assets.coingecko.com/coins/images/38927/small/monad.jpg',
  berachain: 'https://assets.coingecko.com/coins/images/25235/small/berachain.jpeg',
  flare: 'https://assets.coingecko.com/coins/images/28705/small/flare.png',
  sonic: 'https://assets.coingecko.com/coins/images/38108/small/sonic-token.png',
  hyperliquid:
    'https://coin-images.coingecko.com/coins/images/50882/small/hyperliquid.jpg',
  bnb: 'https://assets.coingecko.com/coins/images/825/small/bnb-icon2_2x.png',
  binancecoin: 'https://assets.coingecko.com/coins/images/825/small/bnb-icon2_2x.png',
  tether: 'https://assets.coingecko.com/coins/images/325/small/Tether.png',
  'usd-coin': 'https://assets.coingecko.com/coins/images/6319/small/usdc.png',
  pancakeswap: 'https://assets.coingecko.com/coins/images/12632/small/pancakeswap-cake-logo_%281%29.png',
  uniswap: 'https://assets.coingecko.com/coins/images/12504/small/uni.jpg',
  aave: 'https://assets.coingecko.com/coins/images/12645/small/AAVE.png',
  lido: 'https://assets.coingecko.com/coins/images/13573/small/Lido_DAO.png',
  curve: 'https://assets.coingecko.com/coins/images/12124/small/Curve.png',
  maker: 'https://assets.coingecko.com/coins/images/1364/small/Mark_Maker.png',
  frax: 'https://assets.coingecko.com/coins/images/13422/small/FRAX_icon.png',
  celo: 'https://assets.coingecko.com/coins/images/11090/small/icon_celo_0_73_2.png',
  'nasdaq-xstock':
    'https://coin-images.coingecko.com/coins/images/66696/thumb/QQQx.png',
  'sp500-xstock':
    'https://coin-images.coingecko.com/coins/images/66695/thumb/Ticker_SPX__Company_Name_SP500__size_200x200_2x.png',
  'nvidia-xstock':
    'https://coin-images.coingecko.com/coins/images/55633/thumb/Ticker_NVDA__Company_Name_NVIDIA_Corp__size_200x200_2x.png',
  'tesla-xstock':
    'https://coin-images.coingecko.com/coins/images/55638/thumb/Ticker_TSLA__Company_Name_Tesla_Inc.__size_200x200_2x.png',
  'microsoft-xstock':
    'https://coin-images.coingecko.com/coins/images/55630/thumb/Ticker_MSFT__Company_Name_Microsoft_Inc.__size_200x200_2x.png',
  'alphabet-xstock':
    'https://coin-images.coingecko.com/coins/images/55610/thumb/Ticker_GOOG__Company_Name_Alphabet_Inc.__size_200x200_2x.png',
  'meta-xstock':
    'https://coin-images.coingecko.com/coins/images/55628/thumb/Ticker_META__Company_Name_Meta_Platforms_Inc.__size_200x200_2x.png',
  'amazon-xstock':
    'https://coin-images.coingecko.com/coins/images/55590/thumb/Ticker_AMZN__Company_Name_Amazon.com_Inc.__size_200x200_2x.png',
  'microstrategy-xstock':
    'https://coin-images.coingecko.com/coins/images/55631/thumb/Ticker_MSTR__Company_Name_MicroStrategy__size_200x200_2x.png',
  'exxon-mobil-xstock':
    'https://coin-images.coingecko.com/coins/images/55644/thumb/Ticker_XOM__Company_Name_ExxonMobil__size_200x200_2x.png',
}

/** Símbolos comuns no par (ticker) → logo CoinGecko. */
export const SYMBOL_LOGO_URL: Record<string, string> = {
  BTC: COINGECKO_LOGO_BY_ID.bitcoin,
  WBTC: 'https://assets.coingecko.com/coins/images/7598/small/wrapped_bitcoin_wbtc.png',
  ETH: COINGECKO_LOGO_BY_ID.ethereum,
  WETH: 'https://assets.coingecko.com/coins/images/2518/small/weth.png',
  STETH: 'https://assets.coingecko.com/coins/images/13442/small/steth_logo.png',
  WSTETH: 'https://assets.coingecko.com/coins/images/18834/small/wsteth.png',
  SOL: COINGECKO_LOGO_BY_ID.solana,
  WSOL: COINGECKO_LOGO_BY_ID.solana,
  USDC: 'https://assets.coingecko.com/coins/images/6319/small/usdc.png',
  USDT: 'https://assets.coingecko.com/coins/images/325/small/Tether.png',
  DAI: 'https://assets.coingecko.com/coins/images/9956/small/Badge_Dai.png',
  BNB: COINGECKO_LOGO_BY_ID.bnb,
  WBNB: COINGECKO_LOGO_BY_ID.bnb,
  AVAX: COINGECKO_LOGO_BY_ID.avalanche,
  WAVAX: COINGECKO_LOGO_BY_ID.avalanche,
  MATIC: COINGECKO_LOGO_BY_ID.polygon,
  POL: COINGECKO_LOGO_BY_ID.polygon,
  WMATIC: COINGECKO_LOGO_BY_ID.polygon,
  OP: COINGECKO_LOGO_BY_ID.optimism,
  ARB: COINGECKO_LOGO_BY_ID.arbitrum,
  LINK: COINGECKO_LOGO_BY_ID.chainlink,
  DOGE: COINGECKO_LOGO_BY_ID.dogecoin,
  TRUMP: 'https://assets.coingecko.com/coins/images/53746/small/trump.png',
  HYPE: COINGECKO_LOGO_BY_ID.hyperliquid,
  CBBTC: 'https://assets.coingecko.com/coins/images/40143/small/cbbtc.png',
  CBETH: 'https://assets.coingecko.com/coins/images/27008/small/cbeth.png',
  WEETH: 'https://assets.coingecko.com/coins/images/33033/small/weETH.png',
  RETH: 'https://assets.coingecko.com/coins/images/13508/small/ren.png',
  CAKE: COINGECKO_LOGO_BY_ID.pancakeswap,
  FTM: 'https://assets.coingecko.com/coins/images/4001/small/Fantom_round.png',
  WFTM: 'https://assets.coingecko.com/coins/images/4001/small/Fantom_round.png',
  XRP: COINGECKO_LOGO_BY_ID.ripple,
  ADA: COINGECKO_LOGO_BY_ID.cardano,
  TON: COINGECKO_LOGO_BY_ID.ton,
  SUI: COINGECKO_LOGO_BY_ID.sui,
  APT: COINGECKO_LOGO_BY_ID.aptos,
  OSMO: COINGECKO_LOGO_BY_ID.osmosis,
  ATOM: COINGECKO_LOGO_BY_ID.cosmos,
  NEAR: COINGECKO_LOGO_BY_ID.near,
  LDO: 'https://assets.coingecko.com/coins/images/13573/small/Lido_DAO.png',
  CRV: COINGECKO_LOGO_BY_ID.curve,
  GMX: 'https://assets.coingecko.com/coins/images/18323/small/arbit.png',
  PENDLE: 'https://assets.coingecko.com/coins/images/15069/small/Pendle_Logo_Normal-03.png',
  AERO: 'https://assets.coingecko.com/coins/images/31745/small/token.png',
  VIRTUAL: 'https://assets.coingecko.com/coins/images/34057/small/LOGOMARK.png',
  BRETT: 'https://assets.coingecko.com/coins/images/35529/small/brett.jpg',
  JUP: 'https://assets.coingecko.com/coins/images/34188/small/jup.png',
  RAY: 'https://assets.coingecko.com/coins/images/17580/small/ray.png',
  ORCA: 'https://assets.coingecko.com/coins/images/17547/small/Orca_Logo.png',
  BONK: 'https://assets.coingecko.com/coins/images/28600/small/bonk.jpg',
  MSOL: 'https://assets.coingecko.com/coins/images/17752/small/mSOL.png',
  JITOSOL: 'https://assets.coingecko.com/coins/images/28046/small/JitoSOL.png',
  BSOL: 'https://assets.coingecko.com/coins/images/28415/small/bsol.png',
  UNI: COINGECKO_LOGO_BY_ID.uniswap,
  AAVE: COINGECKO_LOGO_BY_ID.aave,
  MKR: COINGECKO_LOGO_BY_ID.maker,
  SNX: 'https://assets.coingecko.com/coins/images/3406/small/SNX.png',
  FRAX: COINGECKO_LOGO_BY_ID.frax,
  FXS: 'https://assets.coingecko.com/coins/images/13423/small/Frax_Share_icon.png',
  TIA: 'https://assets.coingecko.com/coins/images/31967/small/tia.jpg',
  INJ: 'https://assets.coingecko.com/coins/images/12882/small/Secondary_Symbol.png',
  SEI: 'https://assets.coingecko.com/coins/images/28205/small/Sei_Logo_-_Transparent.png',
  TAO: 'https://assets.coingecko.com/coins/images/28256/small/bittensor.png',
  WLD: 'https://assets.coingecko.com/coins/images/31069/small/worldcoin.jpeg',
  PEPE: 'https://assets.coingecko.com/coins/images/29850/small/pepe-token.jpeg',
  SHIB: 'https://assets.coingecko.com/coins/images/11939/small/shiba.png',
  ONDO: 'https://assets.coingecko.com/coins/images/26580/small/ONDO.png',
  USDY: 'https://assets.coingecko.com/coins/images/31701/small/usdy.png',
  QQQX: COINGECKO_LOGO_BY_ID['nasdaq-xstock'],
  SPYX: COINGECKO_LOGO_BY_ID['sp500-xstock'],
  NVDAX: COINGECKO_LOGO_BY_ID['nvidia-xstock'],
  TSLAX: COINGECKO_LOGO_BY_ID['tesla-xstock'],
  MSFTX: COINGECKO_LOGO_BY_ID['microsoft-xstock'],
  GOOGLX: COINGECKO_LOGO_BY_ID['alphabet-xstock'],
  METAX: COINGECKO_LOGO_BY_ID['meta-xstock'],
  AMZNX: COINGECKO_LOGO_BY_ID['amazon-xstock'],
  MSTRX: COINGECKO_LOGO_BY_ID['microstrategy-xstock'],
  XOMX: COINGECKO_LOGO_BY_ID['exxon-mobil-xstock'],
  XAUT: 'https://assets.coingecko.com/coins/images/10481/small/Tether_Gold.png',
  PAXG: 'https://assets.coingecko.com/coins/images/9519/small/paxgold.png',
  PYUSD: 'https://assets.coingecko.com/coins/images/31212/small/PYUSD_Logo.png',
  EURC: 'https://assets.coingecko.com/coins/images/26045/small/euro-coin.png',
}
